models:
  - name: convnet

    launchers:
      - framework: dlsdk
        device: CPU

        model: convnet.xml
        weights: convnet.bin
        adapter: classification

    datasets:
      - name: mnist
        annotation: annotation/mnist.pickle
        dataset_meta: annotation/mnist.json
        data_source: data/MNIST/raw/converted_images
        reader: pillow_imread

        preprocessing:
          - type: rgb_to_gray  

        metrics:
          - type: accuracy

