model:
  model_name: resnet-50
  model: model/resnet-50.xml
  weights: model/resnet-50.bin

engine:
  config: config/resnet-50.yaml

compression:
  algorithms:
  - name: DefaultQuantization
    params:
      preset: mixed
      stat_subset_size: 100
